language: node_js

node_js:
  - "node"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run-script test-ci

addons:
  code_climate:
    repo_token: 690a4bcbd83d1dc01db7902f1ef3c477fc43e5c32de0f2b4ee8e5ce4a586a5f4