language: node_js

node_js:
  - "node"
  - "iojs"

before_script:
  - bower install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mv server/config.json.default server/config.json

script:
  - npm run-script test-ci