language: node_js

node_js:
  - "node"

addons:
  apt:
    packages:
      - parallel
  firefox: "43.0"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - >
    echo "Extracting firefox and setting PATH variable..."
    tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
    export PATH="/tmp/firefox:$PATH"
    echo "Using firefox version `firefox --version`"

  - npm run-script test-ci

addons:
  code_climate:
    repo_token: 690a4bcbd83d1dc01db7902f1ef3c477fc43e5c32de0f2b4ee8e5ce4a586a5f4
